dev_saga
RPidlis/axels-test-task pull request #5
Opened 2021-05-17 14:55 UTC by RPidlis

2021-05-17 15:02 UTC, RPidlis commented on src/components/ModalWindowComponent.jsx
> +// )(ModalWindowComponent);
в следующем коммите забрал буду внимательнее

2021-05-17 15:02 UTC, RPidlis commented on src/components/CinemaHallComponent.jsx
> +// export default CinemaHallComponent;
в следующем коммите забрал буду внимательнее

2021-05-18 05:02 UTC, mike-gusiev requested changes

2021-05-18 05:02 UTC, mike-gusiev commented on src/components/CinemaHallComponent.jsx
> +const CinemaHallComponent = ({
вместо такого переноса строк:
```
const CinemaHallComponent = ({
                               sessionSeats,
                               seats,
                               onSeatClick,
                               choizedSeats,
                             }) => (

```

делай такой:
```
const CinemaHallComponent = ({
	sessionSeats,
	seats,
	onSeatClick,
	choizedSeats,
}) => (
```

2021-05-18 05:02 UTC, mike-gusiev commented on src/components/CinemaHallComponent.jsx
> +            variant={isSeatChoized?'info':(isSeatSold ? 'info' : 'outline-info')}
пробелы не расставлены вокруг знака вопроса и двоеточия

2021-05-18 05:02 UTC, mike-gusiev commented on src/redux/ducks/schedule.js
> +        sessions: state.sessions.map((session)=> {
ставь пробелы вокруг =>

2021-05-18 05:02 UTC, mike-gusiev commented on src/redux/ducks/schedule.js
> +          if( session.id===action.payload.id ){
вот так нужно пробелы расставлять в таком случае:

```
if (session.id === action.payload.id) {
	return {...session, saledSeats: [...session.saledSeats, ...action.payload.seats]};
} else {
	return session;
}
```

в чем ошибки:
- пробел ставить между if и скобкой (
- пробелы ставяться вокруг ===
- пробел перед и после curly braces {  }
- точки с запятой не расставил после return

2021-05-18 07:05 UTC, merged