dev_testing
RPidlis/axels-test-task pull request #8
Opened 2021-05-24 13:55 UTC by RPidlis

2021-05-24 19:52 UTC, mike-gusiev requested changes

2021-05-24 19:52 UTC, mike-gusiev commented on src/App.test.tsx
> +import { MemoryRouter } from 'react-router-dom';
создай папку src/tests. и туда повыноси все тесты

2021-05-24 19:52 UTC, mike-gusiev commented on src/App.test.tsx
> +import { render, fireEvent } from './test-utils';
покрой тесты снепшотами

2021-05-24 19:52 UTC, mike-gusiev commented on src/components/CinemaHall.test.tsx
> +test('session button 1 to be disabled', () => {
название теста должно начинаться с глагола. например:
test renders
test loads
test disables

и тд

2021-05-24 19:52 UTC, mike-gusiev commented on src/components/CinemaHall.test.tsx
> +
почисти лишние переносы строк

2021-05-24 19:52 UTC, mike-gusiev commented on src/components/CinemaHall.test.tsx
> +
не вижу describe в этом тесте. везде должен быть describe

2021-05-24 19:52 UTC, mike-gusiev commented on src/redux/ducks/schedule.test.ts
> +  let action = actions.setPurchaseSeats({ id: 1, seats: [1, 2, 3, 4] });
почему let а не const?

2021-05-24 19:52 UTC, mike-gusiev commented on src/test-utils.js
> +	ui,
- сделай переносы нормальными в этом файлы
- убери коменты которые не несут смысловой нагрузки и которые очевидны для тех кто читает твой код

2021-05-25 14:13 UTC, RPidlis commented on src/test-utils.js
> +	ui,
если я по другому делаю в екран не влазит

2021-05-25 14:13 UTC, RPidlis commented on src/test/CinemaHall.test.tsx
> +    expect(component).toMatchSnapshot();
то есть я только здесь его делаю или по всем тестам снизу?

2021-05-26 09:30 UTC, merged